inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - lenient.yml

AllCops:
  TargetRubyVersion: 2.7

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Metrics/BlockLength:
  Exclude:
    - 'test/**/*_test.rb'
